Repository codestates-seb/seb41_main_006, pull requests merged in 2023-01, with the labels that each got.

#4 [BE] chore: 배포 자동화
  .github/workflows/gradle.yml
  server/appsepc.yml
  server/scripts/deploy.sh
Labels: documentation

#5 [BE] chore: 배포 자동화
  .github/workflows/gradle.yml
  server/appsepc.yml
  server/scripts/deploy.sh
Labels: documentation

#6 [BE] chore: 배포 자동화 재시도
  server/scripts/deploy.sh
Labels: documentation

#18 #16 [BE] feat: 회원 엔티티 신규 생성 기능
  server/src/main/java/com/mainproject/server/domain/member/controller/MemberController.java
  server/src/main/java/com/mainproject/server/domain/member/dto/MemberDto.java
  server/src/main/java/com/mainproject/server/domain/member/entity/Member.java
  server/src/main/java/com/mainproject/server/domain/member/mapper/MemberMapper.java
  server/src/main/java/com/mainproject/server/domain/member/repository/MemberRepository.java
  server/src/main/java/com/mainproject/server/domain/member/service/MemberService.java
  server/src/main/resources/application-mg.yml
Labels: feature

#20 #19 [BE] feat: api 게층 및 비지니스 로직 계층에서 발생하는 예외 처리 기능
  server/src/main/java/com/mainproject/server/advice/GlobalExceptionAdvice.java
  server/src/main/java/com/mainproject/server/exception/BusinessLogicException.java
  server/src/main/java/com/mainproject/server/exception/ExceptionCode.java
  server/src/main/java/com/mainproject/server/response/ErrorResponse.java
Labels: feature

#21 #17 [BE]feat: 강아지 엔티티 CRUD 구현
  server/src/main/java/com/mainproject/server/domain/pet/controller/PetController.java
  server/src/main/java/com/mainproject/server/domain/pet/dto/PetDto.java
  server/src/main/java/com/mainproject/server/domain/pet/entity/Pet.java
  server/src/main/java/com/mainproject/server/domain/pet/mapper/PetMapper.java
  server/src/main/java/com/mainproject/server/domain/pet/repository/PetRepository.java
  server/src/main/java/com/mainproject/server/domain/pet/service/PetService.java
  server/src/main/java/com/mainproject/server/exception/ExceptionCode.java
Labels: feature

#28 #27 [BE]feat: global Dto,PageInfo 구현
  server/src/main/java/com/mainproject/server/dto/MultiResponseDto.java
  server/src/main/java/com/mainproject/server/dto/SingleResponseDto.java
  server/src/main/java/com/mainproject/server/response/PageInfo.java
Labels: feature

#30 #29 [BE]feat: auditing 구현
  server/src/main/java/com/mainproject/server/global/auth/audit/Auditable.java
Labels: feature

#32 #31 [BE]feat: 댓글 엔티티 CRUD 구현
  server/src/main/java/com/mainproject/server/domain/comments/controller/CommentsController.java
  server/src/main/java/com/mainproject/server/domain/comments/dto/CommentsDto.java
  server/src/main/java/com/mainproject/server/domain/comments/entity/Comments.java
  server/src/main/java/com/mainproject/server/domain/comments/entity/CommentsLike.java
  server/src/main/java/com/mainproject/server/domain/comments/mapper/CommentsMapper.java
  server/src/main/java/com/mainproject/server/domain/comments/repository/CommentsRepository.java
  server/src/main/java/com/mainproject/server/domain/comments/service/CommentsService.java
  server/src/main/java/com/mainproject/server/exception/ExceptionCode.java
Labels: feature

#33 "#25 [BE] feat: 회원 수정 기능 구현
  server/src/main/java/com/mainproject/server/audit/Auditable.java
  server/src/main/java/com/mainproject/server/domain/comments/entity/Comments.java
  server/src/main/java/com/mainproject/server/domain/comments/entity/CommentsLike.java
  server/src/main/java/com/mainproject/server/domain/member/controller/MemberController.java
  server/src/main/java/com/mainproject/server/domain/member/dto/MemberDto.java
  server/src/main/java/com/mainproject/server/domain/member/entity/Member.java
  server/src/main/java/com/mainproject/server/domain/member/mapper/MemberMapper.java
  server/src/main/java/com/mainproject/server/domain/member/service/MemberService.java
  server/src/main/java/com/mainproject/server/exception/ExceptionCode.java
  server/src/main/java/com/mainproject/server/utils/CustomBeanUtils.java
  server/src/main/java/com/mainproject/server/validator/NotSpace.java
  server/src/main/java/com/mainproject/server/validator/NotSpaceValidator.java
Labels: feature

#34 #24 [BE]feat: Board CRUD 구현
  server/src/main/java/com/mainproject/server/domain/board/controller/BoardController.java
  server/src/main/java/com/mainproject/server/domain/board/dto/BoardDto.java
  server/src/main/java/com/mainproject/server/domain/board/entity/Board.java
  server/src/main/java/com/mainproject/server/domain/board/mapper/BoardMapper.java
  server/src/main/java/com/mainproject/server/domain/board/repository/BoardRepository.java
  server/src/main/java/com/mainproject/server/domain/board/service/BoardService.java
  server/src/main/java/com/mainproject/server/exception/ExceptionCode.java
Labels: feature

#37 #36 [BE] feat: 회원 탈퇴 기능
  server/src/main/java/com/mainproject/server/domain/member/controller/MemberController.java
  server/src/main/java/com/mainproject/server/domain/member/service/MemberService.java
  server/src/main/resources/application-mg.yml
Labels: feature

#39 #38 [BE] feat: 마이 페이지 회원 정보 조회
  server/src/main/java/com/mainproject/server/domain/member/controller/MemberController.java
  server/src/main/java/com/mainproject/server/domain/member/service/MemberService.java
Labels: feature

#40 #31 [BE]feat: 댓글 멤버, 게시글 연관관계 매핑
  server/src/main/java/com/mainproject/server/domain/comments/dto/CommentsDto.java
  server/src/main/java/com/mainproject/server/domain/comments/entity/Comments.java
  server/src/main/java/com/mainproject/server/domain/comments/mapper/CommentsMapper.java
  server/src/main/java/com/mainproject/server/domain/comments/service/CommentsService.java
Labels: feature

#46 #45 [BE]feat: gender validation annotation 작성
  server/src/main/java/com/mainproject/server/domain/pet/controller/PetController.java
  server/src/main/java/com/mainproject/server/domain/pet/dto/PetDto.java
  server/src/main/java/com/mainproject/server/domain/pet/entity/Pet.java
  server/src/main/java/com/mainproject/server/domain/pet/mapper/PetMapper.java
  server/src/main/java/com/mainproject/server/domain/pet/repository/PetRepository.java
  server/src/main/java/com/mainproject/server/domain/pet/service/PetService.java
  server/src/main/java/com/mainproject/server/validator/Gender.java
  server/src/main/java/com/mainproject/server/validator/GenderValidator.java
Labels: feature

#47 #26 [BE]fix: PetDto 수정
  server/src/main/java/com/mainproject/server/domain/pet/dto/PetDto.java
Labels: fix

#51 #49 [BE]fix: 댓글좋아요 엔티티 수정
  server/src/main/java/com/mainproject/server/ServerApplication.java
  server/src/main/java/com/mainproject/server/domain/comments/dto/CommentsDto.java
  server/src/main/java/com/mainproject/server/domain/comments/entity/CommentsLike.java
Labels: fix

#55 #50 [BE]fix: board-comments 연관 관계 매핑
  server/src/main/java/com/mainproject/server/domain/board/controller/BoardController.java
  server/src/main/java/com/mainproject/server/domain/board/dto/BoardDto.java
  server/src/main/java/com/mainproject/server/domain/board/entity/Board.java
  server/src/main/java/com/mainproject/server/domain/board/repository/BoardRepository.java
  server/src/main/java/com/mainproject/server/domain/board/service/BoardService.java
Labels: fix

#58 #42 [FE] 모임 글 페이지 마크업
  client/.eslintrc.json
  client/src/App.js
  client/src/components/Button.js
  client/src/components/Map.js
  client/src/pages/PostDetailPage.js
  client/src/pages/PostEditPage.js
  client/src/pages/PostPage.js
Labels: design

#60 #59 [BE]feat: 댓글 좋아요 구현
  server/src/main/java/com/mainproject/server/domain/comments/controller/CommentsController.java
  server/src/main/java/com/mainproject/server/domain/comments/dto/CommentsLikeDto.java
  server/src/main/java/com/mainproject/server/domain/comments/entity/Comments.java
  server/src/main/java/com/mainproject/server/domain/comments/entity/CommentsLike.java
  server/src/main/java/com/mainproject/server/domain/comments/mapper/CommentsMapper.java
  server/src/main/java/com/mainproject/server/domain/comments/repository/CommentsLikeRepository.java
  server/src/main/java/com/mainproject/server/domain/comments/service/CommentsLikeService.java
Labels: feature

#68 #42 [FE] design: 모임 글 상세페이지 마크업 수정
  client/src/App.js
  client/src/components/Button.js
  client/src/components/Map.js
  client/src/components/matePost/AddComment.js
  client/src/components/matePost/Comment.js
  client/src/components/matePost/CommentList.js
  client/src/components/matePost/Recomment.js
  client/src/components/matePost/RecommentList.js
  client/src/pages/PostDetailPage.js
  client/src/pages/PostEditPage.js
  client/src/pages/PostPage.js
  client/src/static/dummyData.js
Labels: design

#67 Fe/feat/43 find mate UI
  client/src/components/Header.js
  client/src/components/common/Button.js
  client/src/components/common/ProfileImage.js
  client/src/components/common/Title.js
  client/src/components/findMate/MatePostCard.js
  client/src/components/findMate/MatePostList.js
  client/src/components/findMate/MatePostsContent.js
  client/src/components/findMate/MateUserCard.js
  client/src/components/findMate/MateUserList.js
  client/src/components/findMate/MateUsersContent.js
  client/src/components/findMate/SearchAddressBox.js
  client/src/components/findMate/UserFilterForm.js
  client/src/components/findMate/UserFilterModal.js
  client/src/hooks/useForm.js
  client/src/pages/FindMatePage.js
  client/src/static/dummyData.js
  client/src/static/userFilterList.js
  client/src/style/styleUtils.js
  client/src/style/styleVariable.js
  client/src/utils/validate.js
Labels: design

#69 #56 [BE]fix: board repo,status 수정
  server/build.gradle
  server/src/main/java/com/mainproject/server/ServerApplication.java
  server/src/main/java/com/mainproject/server/batch/BatchConfig.java
  server/src/main/java/com/mainproject/server/batch/BoardScheduler.java
  server/src/main/java/com/mainproject/server/batch/BoardTasklet.java
  server/src/main/java/com/mainproject/server/domain/board/controller/BoardController.java
  server/src/main/java/com/mainproject/server/domain/board/entity/Board.java
  server/src/main/java/com/mainproject/server/domain/board/repository/BoardRepository.java
  server/src/main/java/com/mainproject/server/domain/board/service/BoardService.java
  server/src/main/java/com/mainproject/server/validator/Gender.java
  server/src/main/java/com/mainproject/server/validator/GenderValidator.java
  server/src/main/resources/application-hr.yml
Labels: fix

#71 #63 [BE]feat: 댓글 대댓글 등록 구현
  server/src/main/java/com/mainproject/server/domain/board/entity/Board.java
  server/src/main/java/com/mainproject/server/domain/comments/controller/CommentsController.java
  server/src/main/java/com/mainproject/server/domain/comments/dto/CommentsDto.java
  server/src/main/java/com/mainproject/server/domain/comments/entity/Comments.java
  server/src/main/java/com/mainproject/server/domain/comments/mapper/CommentsMapper.java
  server/src/main/java/com/mainproject/server/domain/comments/service/CommentsService.java
Labels: feature

#73 #64 [BE] feat: jwt login 기능
  server/.gitignore
  server/build.gradle
  server/src/main/java/com/mainproject/server/auth/JwtTokenizer.java
  server/src/main/java/com/mainproject/server/auth/dto/LoginDto.java
  server/src/main/java/com/mainproject/server/auth/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/mainproject/server/auth/handler/MemberAuthenticationFailureHandler.java
  server/src/main/java/com/mainproject/server/auth/handler/MemberAuthenticationSuccessHandler.java
  server/src/main/java/com/mainproject/server/auth/userdetails/MemberDetailsService.java
  server/src/main/java/com/mainproject/server/auth/utils/CustomAuthorityUtils.java
  server/src/main/java/com/mainproject/server/config/SecurityConfiguration.java
  server/src/main/java/com/mainproject/server/domain/member/dto/MemberDto.java
  server/src/main/java/com/mainproject/server/domain/member/entity/Member.java
  server/src/main/java/com/mainproject/server/domain/member/service/MemberService.java
Labels: feature

#75 #56 [BE]fix: scheduled 30분 간격으로 실행
  server/src/main/java/com/mainproject/server/batch/BatchConfig.java
  server/src/main/java/com/mainproject/server/batch/BoardScheduler.java
  server/src/main/java/com/mainproject/server/domain/board/dto/BoardDto.java
  server/src/main/java/com/mainproject/server/domain/board/entity/Board.java
  server/src/test/java/com/mainproject/server/batchTest/BoardBatchTest.java
  server/src/test/java/com/mainproject/server/batchTest/TestBatchConfig.java
Labels: fix

#83 #42 [FE] design: 모임 글 상세페이지 마크업 수정
  client/src/App.js
  client/src/components/Button.js
  client/src/components/DeleteModal.js
  client/src/components/Map.js
  client/src/components/WithdrawalModal.js
  client/src/components/matePost/AddComment.js
  client/src/components/matePost/Comment.js
  client/src/components/matePost/CommentList.js
  client/src/components/matePost/Recomment.js
  client/src/components/matePost/RecommentList.js
  client/src/pages/PostDetailPage.js
  client/src/pages/PostEditPage.js
  client/src/pages/PostPage.js
  client/src/static/dummyData.js
  client/src/utils/dateConvert.js
Labels: design

#89 #76 [BE]fix: createPet에 setMember하면 error 발생
  server/src/main/java/com/mainproject/server/batch/BoardTasklet.java
  server/src/main/java/com/mainproject/server/domain/board/controller/BoardController.java
  server/src/main/java/com/mainproject/server/domain/board/dto/BoardDto.java
  server/src/main/java/com/mainproject/server/domain/board/entity/Board.java
  server/src/main/java/com/mainproject/server/domain/board/mapper/BoardMapper.java
  server/src/main/java/com/mainproject/server/domain/board/service/BoardService.java
  server/src/main/java/com/mainproject/server/domain/pet/controller/PetController.java
  server/src/main/java/com/mainproject/server/domain/pet/dto/PetDto.java
  server/src/main/java/com/mainproject/server/domain/pet/entity/Pet.java
  server/src/main/java/com/mainproject/server/domain/pet/service/PetService.java
  server/src/main/java/com/mainproject/server/exception/ExceptionCode.java
Labels: fix

#90 #76 [BE]fix: board, pet 회원 정보 적용 완료
  server/src/main/java/com/mainproject/server/auth/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/mainproject/server/auth/filter/JwtVerificationFilter.java
  server/src/main/java/com/mainproject/server/auth/userdetails/MemberDetails.java
  server/src/main/java/com/mainproject/server/auth/userdetails/MemberDetailsService.java
  server/src/main/java/com/mainproject/server/domain/board/controller/BoardController.java
  server/src/main/java/com/mainproject/server/domain/board/dto/BoardDto.java
  server/src/main/java/com/mainproject/server/domain/board/service/BoardService.java
  server/src/main/java/com/mainproject/server/domain/member/entity/Member.java
  server/src/main/java/com/mainproject/server/domain/pet/controller/PetController.java
  server/src/main/java/com/mainproject/server/domain/pet/dto/PetDto.java
  server/src/main/java/com/mainproject/server/domain/pet/entity/Pet.java
  server/src/main/java/com/mainproject/server/domain/pet/service/PetService.java
  server/src/main/resources/application-hr.yml
Labels: bug, fix

#92 #63 [BE]feat: 댓글, 대댓글 정렬 완료
  server/src/main/java/com/mainproject/server/domain/board/controller/BoardController.java
  server/src/main/java/com/mainproject/server/domain/board/service/BoardService.java
  server/src/main/java/com/mainproject/server/domain/comments/controller/CommentsController.java
  server/src/main/java/com/mainproject/server/domain/comments/entity/Comments.java
  server/src/main/java/com/mainproject/server/domain/comments/repository/CommentsRepository.java
  server/src/main/java/com/mainproject/server/domain/comments/service/CommentsService.java
Labels: feature

#93 #63 [BE]move: BoardService에서 CommentsService로 이동
  server/src/main/java/com/mainproject/server/domain/board/service/BoardService.java
  server/src/main/java/com/mainproject/server/domain/comments/service/CommentsService.java
Labels: refator

#97 [BE] feat: refresh 토큰을 이용한 access 토큰 재발급
  server/build.gradle
  server/src/main/java/com/mainproject/server/auth/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/mainproject/server/auth/filter/JwtReissueFilter.java
  server/src/main/java/com/mainproject/server/auth/filter/JwtVerificationFilter.java
  server/src/main/java/com/mainproject/server/auth/handler/MemberAuthenticationSuccessHandler.java
  server/src/main/java/com/mainproject/server/auth/service/RedisService.java
  server/src/main/java/com/mainproject/server/batch/BatchConfig.java
  server/src/main/java/com/mainproject/server/batch/BoardScheduler.java
  server/src/main/java/com/mainproject/server/batch/BoardTasklet.java
  server/src/main/java/com/mainproject/server/config/RedisConfig.java
  server/src/main/java/com/mainproject/server/config/SecurityConfiguration.java
  server/src/main/resources/application-mg.yml
Labels: feature

#100 [BE] feat: logout 기능 구현
  server/src/main/java/com/mainproject/server/auth/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/mainproject/server/auth/filter/JwtLogoutFilter.java
  server/src/main/java/com/mainproject/server/auth/filter/JwtReissueFilter.java
  server/src/main/java/com/mainproject/server/auth/filter/JwtVerificationFilter.java
  server/src/main/java/com/mainproject/server/auth/handler/MemberAuthenticationEntryPoint.java
  server/src/main/java/com/mainproject/server/auth/service/RedisService.java
  server/src/main/java/com/mainproject/server/config/SecurityConfiguration.java
  server/src/main/resources/application-mg.yml
Labels: feature

#103 [BE] docs: 스프링 부트 로깅 설정
  server/.gitignore
  server/src/main/resources/application.yml
  server/src/main/resources/logback-local.properties
  server/src/main/resources/logback-spring.xml
Labels: documentation

#105 [BE]feat: address 관련 코드 생성
  server/build.gradle
  server/src/main/java/com/mainproject/server/domain/address/Controller/AddressController.java
  server/src/main/java/com/mainproject/server/domain/address/Entity/NumberAddress.java
  server/src/main/java/com/mainproject/server/domain/address/Entity/NumberAddressId.java
  server/src/main/java/com/mainproject/server/domain/address/Entity/RoadAddress.java
  server/src/main/java/com/mainproject/server/domain/address/repository/NumberAddressRepository.java
  server/src/main/java/com/mainproject/server/domain/address/repository/RoadAddressRepository.java
  server/src/main/java/com/mainproject/server/domain/address/service/AddressService.java
  server/src/main/resources/application-jh.yml
Labels: feature

#108 [FEAT] 지도 API 적용
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/components/matePost/Map.js
  client/src/components/matePost/MapContainer.js
  client/src/pages/PostDetailPage.js
  client/src/pages/PostEditPage.js
  client/src/pages/PostPage.js
Labels: feature

#111 Be/feat/106 verify email
  server/build.gradle
  server/src/main/java/com/mainproject/server/advice/GlobalExceptionAdvice.java
  server/src/main/java/com/mainproject/server/auth/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/mainproject/server/auth/filter/JwtLogoutFilter.java
  server/src/main/java/com/mainproject/server/auth/filter/JwtReissueFilter.java
  server/src/main/java/com/mainproject/server/auth/filter/JwtVerificationFilter.java
  server/src/main/java/com/mainproject/server/config/SecurityConfiguration.java
  server/src/main/java/com/mainproject/server/helper/email/EmailConfiguration.java
  server/src/main/java/com/mainproject/server/helper/email/EmailController.java
  server/src/main/java/com/mainproject/server/helper/email/EmailDto.java
  server/src/main/java/com/mainproject/server/helper/email/EmailService.java
  server/src/main/java/com/mainproject/server/response/ErrorResponse.java
  server/src/main/resources/application.yml
  server/src/main/resources/templates/mailTemplate.html
Labels: feature

#117 #35 [BE]feat: chat 기본 설정
  server/build.gradle
  server/src/main/java/com/mainproject/server/batch/BatchConfig.java
  server/src/main/java/com/mainproject/server/batch/BoardScheduler.java
  server/src/main/java/com/mainproject/server/batch/BoardTasklet.java
  server/src/main/java/com/mainproject/server/config/RedisConfig.java
  server/src/main/java/com/mainproject/server/config/WebSocketConfig.java
  server/src/main/java/com/mainproject/server/domain/board/controller/BoardController.java
  server/src/main/java/com/mainproject/server/domain/chat/controller/ChatController.java
  server/src/main/java/com/mainproject/server/domain/chat/entity/ChatMessage.java
  server/src/main/java/com/mainproject/server/domain/chat/entity/ChatRoom.java
  server/src/main/java/com/mainproject/server/domain/chat/entity/JoinChat.java
  server/src/main/java/com/mainproject/server/domain/chat/redis/RedisPublisher.java
  server/src/main/java/com/mainproject/server/domain/chat/redis/RedisSubscriber.java
  server/src/main/java/com/mainproject/server/domain/chat/repository/ChatRepository.java
  server/src/main/java/com/mainproject/server/domain/chat/repository/RoomRepository.java
  server/src/main/java/com/mainproject/server/domain/chat/service/ChatService.java
  server/src/main/java/com/mainproject/server/domain/chat/service/RoomService.java
  server/src/main/java/com/mainproject/server/domain/member/entity/Member.java
  server/src/main/java/com/mainproject/server/domain/pet/controller/PetController.java
  server/src/main/java/com/mainproject/server/domain/pet/service/PetService.java
  server/src/main/java/com/mainproject/server/exception/ExceptionCode.java
  server/src/main/resources/application-hr.yml
Labels: feature

#120 #119 [BE]fix: 게시글 작성 시, 회원의 강아지 선택 로직 구현
  server/src/main/java/com/mainproject/server/domain/board/dto/BoardDto.java
  server/src/main/java/com/mainproject/server/domain/board/entity/Board.java
  server/src/main/java/com/mainproject/server/domain/board/mapper/BoardMapper.java
  server/src/main/java/com/mainproject/server/domain/board/service/BoardService.java
  server/src/main/java/com/mainproject/server/domain/pet/controller/PetController.java
  server/src/main/java/com/mainproject/server/domain/pet/dto/PetDto.java
  server/src/main/java/com/mainproject/server/domain/pet/mapper/PetMapper.java
  server/src/main/java/com/mainproject/server/domain/pet/repository/PetRepository.java
  server/src/main/java/com/mainproject/server/domain/pet/service/PetService.java
Labels: feature, fix

#123 #122 [BE]fix: 댓글, 대댓글 response에 nickName 나오도록 수정
  server/src/main/java/com/mainproject/server/domain/board/mapper/BoardMapper.java
  server/src/main/java/com/mainproject/server/domain/comments/dto/CommentsDto.java
  server/src/main/java/com/mainproject/server/domain/comments/entity/Comments.java
  server/src/main/java/com/mainproject/server/domain/comments/service/CommentsService.java
Labels: fix

#125 Be/feat/112 members with address
  server/build.gradle
  server/src/main/java/com/mainproject/server/domain/member/controller/MemberController.java
  server/src/main/java/com/mainproject/server/domain/member/dto/MemberDto.java
  server/src/main/java/com/mainproject/server/domain/member/entity/Member.java
  server/src/main/java/com/mainproject/server/domain/member/mapper/MemberMapper.java
  server/src/main/java/com/mainproject/server/domain/member/repository/MemberRepository.java
  server/src/main/java/com/mainproject/server/domain/member/service/MemberService.java
  server/src/main/java/com/mainproject/server/domain/pet/dto/PetDto.java
  server/src/main/java/com/mainproject/server/domain/pet/mapper/PetMapper.java
  server/src/main/java/com/mainproject/server/helper/email/EmailController.java
  server/src/main/java/com/mainproject/server/validator/GenderValidator.java
  server/src/main/java/com/mainproject/server/validator/MemberAge.java
  server/src/main/java/com/mainproject/server/validator/MemberAgeValidator.java
  server/src/main/java/com/mainproject/server/validator/MemberStatus.java
  server/src/main/java/com/mainproject/server/validator/MemberStatusValidator.java
  server/src/main/java/com/mainproject/server/validator/NotSpaceValidator.java
  server/src/main/resources/application-mg.yml
  server/src/test/java/com/mainproject/server/domain/member/controller/MemberControllerTest.java
Labels: feature

#127 [BE] feat: 특정 회원 정보 조회(강아지 정보 포함)
  server/src/main/java/com/mainproject/server/domain/chat/repository/RoomRepository.java
  server/src/main/java/com/mainproject/server/domain/member/controller/MemberController.java
  server/src/main/java/com/mainproject/server/domain/member/service/MemberService.java
Labels: feature

#128 #35 [BE]fix: 채팅 시큐리티 적용을 위해 설정 변경
  server/src/main/java/com/mainproject/server/auth/JwtTokenizer.java
  server/src/main/java/com/mainproject/server/batch/BoardScheduler.java
  server/src/main/java/com/mainproject/server/batch/BoardTasklet.java
  server/src/main/java/com/mainproject/server/config/SecurityConfiguration.java
  server/src/main/java/com/mainproject/server/config/WebSocketConfig.java
  server/src/main/java/com/mainproject/server/domain/board/dto/BoardDto.java
  server/src/main/java/com/mainproject/server/domain/board/entity/Board.java
  server/src/main/java/com/mainproject/server/domain/chat/controller/ChatController.java
  server/src/main/java/com/mainproject/server/domain/chat/dto/ChatDto.java
  server/src/main/java/com/mainproject/server/domain/chat/entity/ChatMessage.java
  server/src/main/java/com/mainproject/server/domain/chat/entity/ChatRoom.java
  server/src/main/java/com/mainproject/server/domain/chat/handler/StompHandler.java
  server/src/main/java/com/mainproject/server/domain/chat/repository/RoomRepository.java
  server/src/main/java/com/mainproject/server/domain/chat/service/ChatService.java
  server/src/main/java/com/mainproject/server/domain/chat/service/RoomService.java
Labels: fix

#130 #104 [BE]fix: 주소 엔티티명 수정
  server/src/main/java/com/mainproject/server/domain/address/entity/MergedAddress.java
  server/src/main/resources/application-jh.yml
Labels: fix

#133 #119 [BE]fix: board, pet Response Dto 변경
  server/src/main/java/com/mainproject/server/domain/board/dto/BoardDto.java
  server/src/main/java/com/mainproject/server/domain/board/mapper/BoardMapper.java
  server/src/main/java/com/mainproject/server/domain/chat/controller/ChatController.java
  server/src/main/java/com/mainproject/server/domain/member/dto/MemberDto.java
  server/src/main/java/com/mainproject/server/domain/member/entity/Member.java
  server/src/main/java/com/mainproject/server/domain/member/mapper/MemberMapper.java
  server/src/main/java/com/mainproject/server/domain/pet/controller/PetController.java
  server/src/main/java/com/mainproject/server/domain/pet/dto/PetDto.java
  server/src/main/java/com/mainproject/server/domain/pet/mapper/PetMapper.java
Labels: fix

#134 [FE] API read 하는 페이지 데이터 가공
  client/src/App.js
  client/src/api/board/board.js
  client/src/api/board/dummyBoards.js
  client/src/api/member/dummyMembers.js
  client/src/api/member/member.js
  client/src/components/BoardStatus.js
  client/src/components/boardDetail/AddComment.js
  client/src/components/boardDetail/BoardMeetInfo.js
  client/src/components/boardDetail/Comment.js
  client/src/components/boardDetail/CommentContainer.js
  client/src/components/boardDetail/CommentList.js
  client/src/components/boardDetail/Map.js
  client/src/components/boardDetail/MapContainer.js
  client/src/components/boardDetail/Recomment.js
  client/src/components/boardDetail/RecommentList.js
  client/src/components/findMate/MateBoardCard.js
  client/src/components/findMate/MateBoardList.js
  client/src/components/findMate/MateMemberCard.js
  client/src/components/findMate/MateMemeberList.js
  client/src/components/myPage/MemberInfoCard.js
  client/src/components/myPage/PetInfo.js
  client/src/pages/BoardDetailPage.js
  client/src/pages/BoardEditPage.js
  client/src/pages/BoardPage.js
  client/src/utils/dateConvert.js
Labels: feature

#137 [FE] feat: 메이트 찾기 기능 구현 및 지도 API 적용
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/api/findMate.js
  client/src/components/DeleteModal.js
  client/src/components/GlobalModal.js
  client/src/components/boardDetail/Map.js
  client/src/components/boardDetail/MapContainer.js
  client/src/components/findMate/SearchAddressBox.js
  client/src/pages/BoardDetailPage.js
  client/src/pages/BoardEditPage.js
  client/src/pages/BoardPage.js
  client/src/pages/FindMatePage.js
Labels: feature

#139 #138 [BE]fix: 좋아요 갯수 response 추가
  server/src/main/java/com/mainproject/server/domain/board/mapper/BoardMapper.java
  server/src/main/java/com/mainproject/server/domain/comments/dto/CommentsDto.java
  server/src/main/java/com/mainproject/server/domain/comments/entity/Comments.java
Labels: fix

#140 #35 [BE]fix: chat 중간 pr
  server/build.gradle
  server/src/main/java/com/mainproject/server/ServerApplication.java
  server/src/main/java/com/mainproject/server/domain/board/controller/BoardController.java
  server/src/main/java/com/mainproject/server/domain/board/dto/BoardDto.java
  server/src/main/java/com/mainproject/server/domain/board/entity/Board.java
  server/src/main/java/com/mainproject/server/domain/board/mapper/BoardMapper.java
  server/src/main/java/com/mainproject/server/domain/board/repository/BoardRepository.java
  server/src/main/java/com/mainproject/server/domain/board/service/BoardService.java
  server/src/main/java/com/mainproject/server/domain/chat/controller/RoomController.java
  server/src/main/java/com/mainproject/server/domain/chat/dto/ChatDto.java
  server/src/main/java/com/mainproject/server/domain/chat/entity/ChatMessage.java
  server/src/main/java/com/mainproject/server/domain/chat/entity/JoinChat.java
  server/src/main/java/com/mainproject/server/domain/chat/redis/RedisPublisher.java
  server/src/main/java/com/mainproject/server/domain/chat/redis/RedisSubscriber.java
  server/src/main/java/com/mainproject/server/domain/chat/repository/RoomRepository.java
  server/src/main/java/com/mainproject/server/domain/chat/service/ChatService.java
  server/src/main/java/com/mainproject/server/domain/chat/service/RoomService.java
  server/src/main/java/com/mainproject/server/domain/comments/service/CommentsService.java
  server/src/main/java/com/mainproject/server/domain/member/entity/Member.java
  server/src/test/java/com/mainproject/server/domain/member/controller/MemberControllerTest.java
Labels: fix

#141 Be/feat/136 email verification
  server/src/main/java/com/mainproject/server/auth/service/RedisService.java
  server/src/main/java/com/mainproject/server/exception/ExceptionCode.java
  server/src/main/java/com/mainproject/server/helper/email/EmailController.java
  server/src/main/java/com/mainproject/server/helper/email/EmailDto.java
  server/src/main/java/com/mainproject/server/helper/email/EmailService.java
Labels: feature

#143 [BE] fix: #142 email verification api path
  server/src/main/java/com/mainproject/server/helper/email/EmailController.java
  server/src/main/resources/application.yml
Labels: fix

#145 [BE] docs: #144 yml 파일 수정
  server/src/main/resources/application.yml
  server/src/test/java/com/mainproject/server/batchTest/BoardBatchTest.java
  server/src/test/java/com/mainproject/server/batchTest/TestBatchConfig.java
Labels: documentation

#148 [BE] docs:#147 restdocs 관련 gradle 설정 삭제
  server/build.gradle
Labels: documentation

#149 [BE] docs: asciidoctor 설정 제외
  server/build.gradle
Labels: documentation

#157 [BE] deploy: 임시 배포 1
  .github/workflows/gradle.yml
  server/src/main/java/com/mainproject/server/domain/chat/entity/ChatMessage.java
  server/src/main/java/com/mainproject/server/domain/chat/entity/ChatRoom.java
  server/src/main/java/com/mainproject/server/domain/chat/entity/JoinChat.java
  server/src/test/resources/application.yml
Labels: fix

#161 [FEAT] 산책 메이트 화면 동 검색, 현재 위치 방식 수정
  client/src/components/DogFootLoading.js
  client/src/components/findMate/SearchAddress.js
  client/src/components/findMate/SearchAddressBox.js
  client/src/pages/FindMatePage.js
Labels: feature, design, fix

#163 #35 [BE]fix: chat 전반적인 수정
  server/build.gradle
  server/src/main/java/com/mainproject/server/config/RedisConfig.java
  server/src/main/java/com/mainproject/server/config/SecurityConfiguration.java
  server/src/main/java/com/mainproject/server/config/WebSocketConfig.java
  server/src/main/java/com/mainproject/server/domain/chat/controller/MessageController.java
  server/src/main/java/com/mainproject/server/domain/chat/controller/RoomController.java
  server/src/main/java/com/mainproject/server/domain/chat/dto/ChatDto.java
  server/src/main/java/com/mainproject/server/domain/chat/dto/MessageDto.java
  server/src/main/java/com/mainproject/server/domain/chat/entity/ChatMessage.java
  server/src/main/java/com/mainproject/server/domain/chat/entity/ChatRoom.java
  server/src/main/java/com/mainproject/server/domain/chat/entity/JoinChat.java
  server/src/main/java/com/mainproject/server/domain/chat/mapper/ChatMapper.java
  server/src/main/java/com/mainproject/server/domain/chat/redis/RedisPublisher.java
  server/src/main/java/com/mainproject/server/domain/chat/redis/RedisSubscriber.java
  server/src/main/java/com/mainproject/server/domain/chat/repository/ChatRepository.java
  server/src/main/java/com/mainproject/server/domain/chat/repository/MessageRepository.java
  server/src/main/java/com/mainproject/server/domain/chat/repository/RoomRepository.java
  server/src/main/java/com/mainproject/server/domain/chat/service/ChatService.java
  server/src/main/java/com/mainproject/server/domain/chat/service/RoomService.java
  server/src/main/java/com/mainproject/server/domain/member/entity/Member.java
  server/src/main/java/com/mainproject/server/helper/chat/StompHandler.java
Labels: feature, fix

#168 #104 [BE]fix: address 미사용 클래스 정리
  server/src/main/java/com/mainproject/server/domain/address/controller/AddressController.java
  server/src/main/java/com/mainproject/server/domain/address/dto/AddressDto.java
  server/src/main/java/com/mainproject/server/domain/address/entity/Address.java
  server/src/main/java/com/mainproject/server/domain/address/entity/MergedAddress.java
  server/src/main/java/com/mainproject/server/domain/address/service/AddressService.java
Labels: fix

#169 #167 [BE]feat: S3 멤버 이미지 업로드 구현
  server/build.gradle
  server/src/main/java/com/mainproject/server/awsS3/config/AwsS3Config.java
  server/src/main/java/com/mainproject/server/awsS3/controller/S3UpFileController.java
  server/src/main/java/com/mainproject/server/awsS3/dto/S3UpFileResponse.java
  server/src/main/java/com/mainproject/server/awsS3/entity/S3UpFile.java
  server/src/main/java/com/mainproject/server/awsS3/repository/S3UpFileRepository.java
  server/src/main/java/com/mainproject/server/awsS3/service/S3UpFileService.java
  server/src/main/resources/application-jh.yml
Labels: feature

#170 #167 [BE]feat: S3 멤버, 펫 이미지 업로드 및 삭제 구현
  server/src/main/java/com/mainproject/server/awsS3/controller/S3UpFileController.java
  server/src/main/java/com/mainproject/server/awsS3/repository/S3UpFileRepository.java
  server/src/main/java/com/mainproject/server/awsS3/service/S3UpFileService.java
  server/src/main/java/com/mainproject/server/exception/ExceptionCode.java
Labels: feature

#171 #167 [BE]fix: S3 Pet, Member 연관관계 매핑 및 response 수정
  .github/workflows/gradle.yml
  server/src/main/java/com/mainproject/server/ServerApplication.java
  server/src/main/java/com/mainproject/server/awsS3/controller/S3UpFileController.java
  server/src/main/java/com/mainproject/server/awsS3/dto/S3UpFileResponse.java
  server/src/main/java/com/mainproject/server/awsS3/entity/S3UpFile.java
  server/src/main/java/com/mainproject/server/awsS3/mapper/S3UpFileMapper.java
  server/src/main/java/com/mainproject/server/awsS3/service/S3UpFileService.java
  server/src/main/java/com/mainproject/server/domain/pet/service/PetService.java
  server/src/main/resources/application-jh.yml
  server/src/main/resources/application.yml
Labels: fix

#172 #167 [BE]fix: 연관관계 매핑 변경
  server/src/main/java/com/mainproject/server/ServerApplication.java
  server/src/main/java/com/mainproject/server/awsS3/controller/S3UpFileController.java
  server/src/main/java/com/mainproject/server/awsS3/dto/S3UpFileResponse.java
  server/src/main/java/com/mainproject/server/awsS3/entity/S3UpFile.java
  server/src/main/java/com/mainproject/server/awsS3/mapper/S3UpFileMapper.java
  server/src/main/java/com/mainproject/server/awsS3/repository/S3UpFileRepository.java
  server/src/main/java/com/mainproject/server/awsS3/service/S3UpFileService.java
  server/src/main/java/com/mainproject/server/domain/member/controller/MemberController.java
  server/src/main/java/com/mainproject/server/domain/member/dto/MemberDto.java
  server/src/main/java/com/mainproject/server/domain/member/entity/Member.java
  server/src/main/java/com/mainproject/server/domain/member/mapper/MemberMapper.java
  server/src/main/java/com/mainproject/server/domain/member/service/MemberService.java
  server/src/main/java/com/mainproject/server/domain/pet/controller/PetController.java
  server/src/main/java/com/mainproject/server/domain/pet/dto/PetDto.java
  server/src/main/java/com/mainproject/server/domain/pet/entity/Pet.java
  server/src/main/java/com/mainproject/server/domain/pet/mapper/PetMapper.java
  server/src/main/java/com/mainproject/server/domain/pet/service/PetService.java
Labels: fix

#177 #176 [BE]fix: board status 수정 못하도록 변경
  server/src/main/java/com/mainproject/server/batch/BoardScheduler.java
  server/src/main/java/com/mainproject/server/config/SecurityConfiguration.java
  server/src/main/java/com/mainproject/server/domain/board/dto/BoardDto.java
  server/src/main/java/com/mainproject/server/domain/board/service/BoardService.java
  server/src/main/java/com/mainproject/server/domain/chat/controller/MessageController.java
  server/src/main/java/com/mainproject/server/domain/chat/controller/RoomController.java
  server/src/main/java/com/mainproject/server/domain/chat/service/ChatService.java
  server/src/main/java/com/mainproject/server/domain/pet/dto/PetDto.java
Labels: fix

#178 #164 [BE]fix: 웹소켓 통신을 위한 시큐리티 수정
  server/build.gradle
  server/src/main/java/com/mainproject/server/config/SecurityConfiguration.java
  server/src/main/java/com/mainproject/server/config/WebSocketConfig.java
  server/src/main/java/com/mainproject/server/domain/chat/controller/MessageController.java
  server/src/main/java/com/mainproject/server/domain/chat/controller/RoomController.java
  server/src/main/java/com/mainproject/server/domain/chat/dto/ChatDto.java
  server/src/main/java/com/mainproject/server/domain/chat/entity/ChatRoom.java
  server/src/main/java/com/mainproject/server/domain/chat/mapper/ChatMapper.java
  server/src/main/java/com/mainproject/server/domain/chat/repository/MessageRepository.java
  server/src/main/java/com/mainproject/server/domain/chat/repository/RoomRepository.java
  server/src/main/java/com/mainproject/server/domain/chat/service/ChatService.java
  server/src/main/java/com/mainproject/server/domain/chat/service/RoomService.java
  server/src/main/java/com/mainproject/server/helper/chat/StompHandler.java
  server/src/main/resources/application-hr.yml
Labels: fix

#185 [BE] fix: #184 pet profile image
  server/src/main/java/com/mainproject/server/awsS3/controller/S3UpFileController.java
  server/src/main/java/com/mainproject/server/awsS3/entity/S3UpFile.java
  server/src/main/java/com/mainproject/server/awsS3/service/S3UpFileService.java
  server/src/main/java/com/mainproject/server/domain/pet/controller/PetController.java
  server/src/main/java/com/mainproject/server/domain/pet/dto/PetDto.java
  server/src/main/java/com/mainproject/server/domain/pet/entity/Pet.java
  server/src/main/java/com/mainproject/server/domain/pet/mapper/PetMapper.java
  server/src/main/java/com/mainproject/server/domain/pet/service/PetService.java
Labels: fix

#187 [BE] fix: #184 pet profile image
  server/src/main/java/com/mainproject/server/awsS3/entity/S3UpFile.java
Labels: fix

#190 [BE] fix: #189 board x,y response
  server/src/main/java/com/mainproject/server/domain/board/mapper/BoardMapper.java
Labels: fix

#191 [BE] feat:#186 profile image dto"
  server/src/main/java/com/mainproject/server/auth/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/mainproject/server/awsS3/entity/S3UpFile.java
  server/src/main/java/com/mainproject/server/domain/chat/service/ChatService.java
  server/src/main/java/com/mainproject/server/domain/member/mapper/MemberMapper.java
  server/src/main/java/com/mainproject/server/domain/pet/controller/PetController.java
  server/src/main/java/com/mainproject/server/domain/pet/dto/PetDto.java
  server/src/main/java/com/mainproject/server/domain/pet/entity/Pet.java
  server/src/main/java/com/mainproject/server/domain/pet/mapper/PetMapper.java
  server/src/main/java/com/mainproject/server/domain/pet/service/PetService.java
Labels: feature, fix

#194 [BE] feat: #193 application-server.yml
  server/src/main/resources/application-jh.yml
  server/src/main/resources/application-server.yml
Labels: feature, fix

#195 [BE] feat:#192 email verification duplicate check
  server/src/main/java/com/mainproject/server/domain/member/service/MemberService.java
  server/src/main/java/com/mainproject/server/helper/email/EmailController.java
Labels: fix

#200 #164 [BE]fix: 웹소켓 통신을 위한 시큐리티 수정
  server/src/main/java/com/mainproject/server/config/SecurityConfiguration.java
  server/src/main/java/com/mainproject/server/config/WebSocketConfig.java
  server/src/main/java/com/mainproject/server/helper/chat/StompHandler.java
Labels: fix

#209 #164 [BE]fix: StompHandler 토큰 유효성 검증 수정
  server/src/main/java/com/mainproject/server/config/WebSocketConfig.java
  server/src/main/java/com/mainproject/server/domain/chat/redis/RedisSubscriber.java
  server/src/main/java/com/mainproject/server/helper/chat/StompHandler.java
Labels: fix

#215 [BE] fix: #214 특정 멤버 조회시 주소값 수정
  server/src/main/java/com/mainproject/server/domain/address/repository/AddressRepository.java
  server/src/main/java/com/mainproject/server/domain/member/service/MemberService.java
  server/src/main/resources/application-jh.yml
Labels: fix

#216 [FEAT] 회원가입 페이지 서버 요청 테스트
  client/package-lock.json
  client/src/api/authRequest.js
  client/src/api/defalutRequest.js
  client/src/api/defaultRequest.js
  client/src/api/image.js
  client/src/api/kakaoMap/getAddressByCode.js
  client/src/api/member/dummyMembers.js
  client/src/api/member/member.js
  client/src/api/member/memberDecodes.js
  client/src/api/member/signup.js
  client/src/components/DogFootLoading.js
  client/src/components/findMate/SearchAddress.js
  client/src/components/myPage/MemberInfo.js
  client/src/components/myPage/Modal/EditMemberModal.js
  client/src/components/signup/EmailAuthModal.js
  client/src/components/signup/MemberInfoInput.js
  client/src/components/signup/SignUp.js
  client/src/hooks/useForm.js
  client/src/pages/SignUpPage.js
  client/src/utils/loginValidate.js
  client/src/utils/signUpValidate.js
  client/src/utils/validateFunctions.js
Labels: bug, feature

#220 [BE] batch schema 수정
  server/src/main/resources/application-server.yml
Labels: fix

#221 [BE] deploy: batch schema
  server/src/main/resources/application-server.yml
Labels: fix

#223 #164 [BE]fix: chat 권한 수정
  server/src/main/java/com/mainproject/server/config/SecurityConfiguration.java
  server/src/main/java/com/mainproject/server/config/WebSocketConfig.java
  server/src/main/java/com/mainproject/server/domain/chat/controller/MessageController.java
  server/src/main/resources/application-server.yml
Labels: fix

#225 [BE] fix: my page response, check duplicate nickname
  server/src/main/java/com/mainproject/server/domain/member/controller/MemberController.java
  server/src/main/java/com/mainproject/server/domain/member/dto/MemberDto.java
  server/src/main/java/com/mainproject/server/domain/member/entity/Member.java
  server/src/main/java/com/mainproject/server/domain/member/mapper/MemberMapper.java
  server/src/main/java/com/mainproject/server/domain/member/repository/MemberRepository.java
  server/src/main/java/com/mainproject/server/domain/member/service/MemberService.java
  server/src/main/java/com/mainproject/server/exception/ExceptionCode.java
  server/src/main/java/com/mainproject/server/helper/email/EmailController.java
  server/src/main/resources/application-mg.yml
  server/src/main/resources/logback-spring.xml
  server/src/main/resources/sql/init.sql
Labels: feature, fix

#228 #227 [BE]refator: board update 수정
  server/src/main/java/com/mainproject/server/domain/board/controller/BoardController.java
  server/src/main/java/com/mainproject/server/domain/board/service/BoardService.java
Labels: refator

#230 [BE] fix: nickname verification api open
  .idea/workspace.xml
  server/src/main/java/com/mainproject/server/config/SecurityConfiguration.java
Labels: fix

#232 #164 [BE]fix: ChannelInterceptor 삭제
  server/src/main/java/com/mainproject/server/config/WebSocketConfig.java
  server/src/main/java/com/mainproject/server/domain/chat/dto/MessageDto.java
  server/src/main/java/com/mainproject/server/domain/chat/redis/RedisSubscriber.java
  server/src/main/java/com/mainproject/server/domain/chat/service/RoomService.java
  server/src/main/java/com/mainproject/server/helper/chat/StompHandler.java
Labels: bug, fix

#237 [FE]feat : 보드 포스트 시 강아지 선택 구현
  client/package-lock.json
  client/package.json
  client/src/components/boardDetail/ChoosePetInfo.js
  client/src/components/chatting/ChatList.js
  client/src/components/chatting/ChatRoom.js
  client/src/pages/BoardPage.js
Labels: feature

#239 #164 [BE]fix: publish message 객체화 클래스 생성
  server/src/main/java/com/mainproject/server/domain/chat/controller/MessageController.java
  server/src/main/java/com/mainproject/server/domain/chat/entity/RedisChat.java
  server/src/main/java/com/mainproject/server/domain/chat/redis/RedisSubscriber.java
Labels: fix

#240 [BE] chat 수정 배포
  server/src/main/java/com/mainproject/server/domain/chat/controller/MessageController.java
  server/src/main/java/com/mainproject/server/domain/chat/entity/RedisChat.java
  server/src/main/java/com/mainproject/server/domain/chat/redis/RedisSubscriber.java
Labels: bug, fix

#241 #164 [BE]fix: MessageMapping 수정
  server/src/main/java/com/mainproject/server/domain/chat/controller/MessageController.java
  server/src/main/java/com/mainproject/server/domain/chat/controller/RoomController.java
  server/src/main/java/com/mainproject/server/domain/chat/dto/MessageDto.java
Labels: bug, fix

#242 [BE] 배포 : 메세지 전송 수정
  server/src/main/java/com/mainproject/server/domain/chat/controller/MessageController.java
  server/src/main/java/com/mainproject/server/domain/chat/controller/RoomController.java
  server/src/main/java/com/mainproject/server/domain/chat/dto/MessageDto.java
Labels: bug, fix

#243 #164 [BE]fix: get board, pet, MessageController 수정
  server/src/main/java/com/mainproject/server/batch/BoardTasklet.java
  server/src/main/java/com/mainproject/server/domain/board/controller/BoardController.java
  server/src/main/java/com/mainproject/server/domain/board/dto/BoardDto.java
  server/src/main/java/com/mainproject/server/domain/board/mapper/BoardMapper.java
  server/src/main/java/com/mainproject/server/domain/board/repository/BoardRepository.java
  server/src/main/java/com/mainproject/server/domain/board/service/BoardService.java
  server/src/main/java/com/mainproject/server/domain/chat/controller/MessageController.java
  server/src/main/java/com/mainproject/server/domain/chat/controller/RoomController.java
  server/src/main/java/com/mainproject/server/domain/pet/controller/PetController.java
Labels: bug, fix

#245 #244 [BE]fix: 마이페이지 이미지 response 수정
  server/src/main/java/com/mainproject/server/domain/member/controller/MemberController.java
  server/src/main/java/com/mainproject/server/domain/member/mapper/MemberMapper.java
Labels: fix

#246 #164 [BE]fix: MessageController 수정
  server/src/main/java/com/mainproject/server/domain/chat/controller/MessageController.java
  server/src/main/java/com/mainproject/server/domain/chat/entity/RedisChat.java
  server/src/main/java/com/mainproject/server/domain/chat/redis/RedisSubscriber.java
Labels: fix

#247 [FIX] findMyPets, findMyBoard, Message 수정
  server/src/main/java/com/mainproject/server/batch/BoardTasklet.java
  server/src/main/java/com/mainproject/server/domain/board/controller/BoardController.java
  server/src/main/java/com/mainproject/server/domain/board/dto/BoardDto.java
  server/src/main/java/com/mainproject/server/domain/board/mapper/BoardMapper.java
  server/src/main/java/com/mainproject/server/domain/board/repository/BoardRepository.java
  server/src/main/java/com/mainproject/server/domain/board/service/BoardService.java
  server/src/main/java/com/mainproject/server/domain/chat/controller/MessageController.java
  server/src/main/java/com/mainproject/server/domain/chat/controller/RoomController.java
  server/src/main/java/com/mainproject/server/domain/chat/entity/RedisChat.java
  server/src/main/java/com/mainproject/server/domain/chat/redis/RedisSubscriber.java
  server/src/main/java/com/mainproject/server/domain/member/controller/MemberController.java
  server/src/main/java/com/mainproject/server/domain/member/mapper/MemberMapper.java
  server/src/main/java/com/mainproject/server/domain/pet/controller/PetController.java
Labels: fix

#249 [BE] bug:#248 logout, reissue 버그 수정
  server/src/main/java/com/mainproject/server/auth/filter/JwtLogoutFilter.java
  server/src/main/java/com/mainproject/server/auth/filter/JwtReissueFilter.java
  server/src/main/java/com/mainproject/server/auth/filter/JwtVerificationFilter.java
  server/src/main/java/com/mainproject/server/auth/handler/MemberAuthenticationEntryPoint.java
  server/src/main/java/com/mainproject/server/auth/utils/ErrorResponder.java
  server/src/main/java/com/mainproject/server/config/SecurityConfiguration.java
  server/src/main/java/com/mainproject/server/domain/member/controller/MemberController.java
  server/src/main/java/com/mainproject/server/domain/member/service/MemberService.java
  server/src/main/resources/sql/init.sql
Labels: bug, fix

#251 #164 [BE]fix: publish 수정
  server/src/main/java/com/mainproject/server/domain/chat/controller/MessageController.java
  server/src/main/java/com/mainproject/server/domain/chat/service/RoomService.java
Labels: fix

#253 #164 [BE]fix: RedisSubscriber implements MessageListener
  server/src/main/java/com/mainproject/server/config/RedisConfig.java
  server/src/main/java/com/mainproject/server/domain/chat/controller/MessageController.java
  server/src/main/java/com/mainproject/server/domain/chat/redis/RedisPublisher.java
  server/src/main/java/com/mainproject/server/domain/chat/redis/RedisSubscriber.java
Labels: fix

#254 [BE] 채팅 또 수정
  server/src/main/java/com/mainproject/server/config/RedisConfig.java
  server/src/main/java/com/mainproject/server/domain/chat/controller/MessageController.java
  server/src/main/java/com/mainproject/server/domain/chat/redis/RedisPublisher.java
  server/src/main/java/com/mainproject/server/domain/chat/redis/RedisSubscriber.java
Labels: fix

#255 #164 [BE]fix: SecurityConfiguration 수정
  server/src/main/java/com/mainproject/server/config/SecurityConfiguration.java
Labels: fix

#256 Dev be 배포
  server/src/main/java/com/mainproject/server/config/SecurityConfiguration.java
Labels: fix

#257 #164 [BE]fix: RedisConfig 수정
  server/src/main/java/com/mainproject/server/config/RedisConfig.java
Labels: bug

#258 Dev be
  server/src/main/java/com/mainproject/server/config/RedisConfig.java
Labels: bug

#259 #164 [BE]fix: RedisConfig 수정
  server/src/main/java/com/mainproject/server/config/RedisConfig.java
Labels: fix

#260 Dev be
  server/src/main/java/com/mainproject/server/config/RedisConfig.java
Labels: fix

#261 #164 [BE]fix: chat 또 수정
  server/src/main/java/com/mainproject/server/config/RedisConfig.java
  server/src/main/java/com/mainproject/server/domain/chat/controller/MessageController.java
  server/src/main/java/com/mainproject/server/domain/chat/service/RoomService.java
Labels: fix

#262 [FIX] 채팅 로직 수정
  server/src/main/java/com/mainproject/server/config/RedisConfig.java
  server/src/main/java/com/mainproject/server/domain/chat/controller/MessageController.java
  server/src/main/java/com/mainproject/server/domain/chat/service/RoomService.java
Labels: fix

#263 #164 [BE]fix: SecurityConfiguration 수정
  server/src/main/java/com/mainproject/server/config/SecurityConfiguration.java
Labels: fix

#264 Dev be
  server/src/main/java/com/mainproject/server/config/SecurityConfiguration.java
Labels: fix

#267 [FEAT, FIX] 마이페이지 서버 오류 해결, 나의 강아지 가져오기
  client/src/api/authRequest.js
  client/src/api/board/board.js
  client/src/api/board/boardDecodes.js
  client/src/api/member/member.js
  client/src/api/pet/pet.js
  client/src/components/common/DogFace.js
  client/src/components/common/DogProfile.js
  client/src/components/common/PetProfileImage.js
  client/src/components/myPage/BoardInfo.js
  client/src/components/myPage/MemberInfoCard.js
  client/src/components/myPage/Modal/AddPetInfoModal.js
  client/src/components/myPage/Modal/EditMemberModal.js
  client/src/components/myPage/PetInfo.js
  client/src/components/myPage/PetInfoInput.js
  client/src/components/signup/MemberInfoInput.js
  client/src/hooks/useForm.js
  client/src/pages/MyPage.js
  client/src/pages/SignUpPage.js
  client/src/static/images/dogFace.svg
  client/src/static/images/dogProfile.svg
  client/src/utils/petInfoValidate.js
  client/src/utils/validateFunctions.js
Labels: bug, feature

#268 #164 [BE]fix: publish 로직 수정
  server/src/main/java/com/mainproject/server/config/RedisConfig.java
  server/src/main/java/com/mainproject/server/config/SecurityConfiguration.java
  server/src/main/java/com/mainproject/server/config/WebSocketConfig.java
  server/src/main/java/com/mainproject/server/domain/chat/controller/MessageController.java
  server/src/main/java/com/mainproject/server/domain/chat/entity/PublishMessage.java
  server/src/main/java/com/mainproject/server/domain/chat/redis/RedisPublisher.java
  server/src/main/java/com/mainproject/server/domain/chat/redis/RedisSubscriber.java
  server/src/main/java/com/mainproject/server/domain/chat/service/ChatService.java
Labels: fix

#269 [BE] FIX : publish 로직 수정
  server/src/main/java/com/mainproject/server/config/RedisConfig.java
  server/src/main/java/com/mainproject/server/config/SecurityConfiguration.java
  server/src/main/java/com/mainproject/server/config/WebSocketConfig.java
  server/src/main/java/com/mainproject/server/domain/chat/controller/MessageController.java
  server/src/main/java/com/mainproject/server/domain/chat/entity/PublishMessage.java
  server/src/main/java/com/mainproject/server/domain/chat/redis/RedisPublisher.java
  server/src/main/java/com/mainproject/server/domain/chat/redis/RedisSubscriber.java
  server/src/main/java/com/mainproject/server/domain/chat/service/ChatService.java
Labels: fix

#270 [BE]fix: path type(long -> Long) 변경
  server/src/main/java/com/mainproject/server/domain/chat/controller/MessageController.java
  server/src/main/java/com/mainproject/server/domain/chat/dto/MessageDto.java
  server/src/main/java/com/mainproject/server/domain/chat/entity/PublishMessage.java
  server/src/main/java/com/mainproject/server/domain/chat/service/ChatService.java
Labels: fix

#271 [BE]fix: path type(long -> Long) 변경
  server/src/main/java/com/mainproject/server/domain/chat/controller/MessageController.java
  server/src/main/java/com/mainproject/server/domain/chat/dto/MessageDto.java
  server/src/main/java/com/mainproject/server/domain/chat/entity/PublishMessage.java
  server/src/main/java/com/mainproject/server/domain/chat/service/ChatService.java
Labels: fix

#272 #164 [BE]fix: 메세지 전송 시, 멤버 정보 가져오는 로직 삭제
  server/src/main/java/com/mainproject/server/domain/chat/controller/MessageController.java
  server/src/main/java/com/mainproject/server/domain/chat/entity/PublishMessage.java
  server/src/main/java/com/mainproject/server/domain/chat/mapper/ChatMapper.java
Labels: fix

#274 #164 [BE]fix: 시큐리티 설정 삭제
  server/src/main/java/com/mainproject/server/domain/chat/controller/MessageController.java
Labels: fix

#275 #164 [BE]fix: 시큐리티 설정 삭제
  server/src/main/java/com/mainproject/server/domain/chat/controller/MessageController.java
Labels: fix

#277 #276 [BE]feature: 대댓글 삭제 api 추가
  server/src/main/java/com/mainproject/server/domain/board/controller/BoardController.java
  server/src/main/java/com/mainproject/server/domain/comments/controller/CommentsController.java
  server/src/main/java/com/mainproject/server/domain/comments/entity/Comments.java
  server/src/main/java/com/mainproject/server/domain/comments/mapper/CommentsMapper.java
  server/src/main/java/com/mainproject/server/domain/comments/service/CommentsService.java
  server/src/main/java/com/mainproject/server/exception/ExceptionCode.java
Labels: feature

#278 #276 [BE]feature: 대댓글 삭제 api 추가 (#277)
  server/src/main/java/com/mainproject/server/domain/board/controller/BoardController.java
  server/src/main/java/com/mainproject/server/domain/comments/controller/CommentsController.java
  server/src/main/java/com/mainproject/server/domain/comments/entity/Comments.java
  server/src/main/java/com/mainproject/server/domain/comments/mapper/CommentsMapper.java
  server/src/main/java/com/mainproject/server/domain/comments/service/CommentsService.java
  server/src/main/java/com/mainproject/server/exception/ExceptionCode.java
Labels: feature

#279 #164 [BE]fix: memberId->senderId
  server/src/main/java/com/mainproject/server/domain/chat/controller/MessageController.java
  server/src/main/java/com/mainproject/server/domain/chat/dto/MessageDto.java
Labels: fix

#280 #164 [BE]fix: memberId->senderId
  server/src/main/java/com/mainproject/server/domain/chat/controller/MessageController.java
  server/src/main/java/com/mainproject/server/domain/chat/dto/MessageDto.java
Labels: fix

#281 #164 [BE]fix: memberId->senderId
  server/src/main/java/com/mainproject/server/domain/chat/service/ChatService.java
Labels: fix

#282 #164 [BE]fix: memberId->senderId
  server/src/main/java/com/mainproject/server/domain/chat/service/ChatService.java
Labels: fix

#283 #164 [BE]fix: chatDto `Serializable` 적용
  server/src/main/java/com/mainproject/server/config/RedisConfig.java
  server/src/main/java/com/mainproject/server/domain/chat/dto/MessageDto.java
  server/src/main/java/com/mainproject/server/domain/chat/entity/ChatMessage.java
  server/src/main/java/com/mainproject/server/domain/chat/entity/PublishMessage.java
  server/src/main/java/com/mainproject/server/domain/chat/redis/RedisSubscriber.java
  server/src/main/java/com/mainproject/server/domain/chat/service/ChatService.java
Labels: fix

#284 #164 [BE]fix: chatDto Serializable 적용
  server/src/main/java/com/mainproject/server/config/RedisConfig.java
  server/src/main/java/com/mainproject/server/domain/chat/dto/MessageDto.java
  server/src/main/java/com/mainproject/server/domain/chat/entity/ChatMessage.java
  server/src/main/java/com/mainproject/server/domain/chat/entity/PublishMessage.java
  server/src/main/java/com/mainproject/server/domain/chat/redis/RedisSubscriber.java
  server/src/main/java/com/mainproject/server/domain/chat/service/ChatService.java
Labels: fix

#285 #164 [BE]fix: redisChat config 분리
  server/src/main/java/com/mainproject/server/config/RedisChatConfig.java
  server/src/main/java/com/mainproject/server/config/RedisConfig.java
  server/src/main/java/com/mainproject/server/domain/chat/entity/ChatMessage.java
  server/src/main/java/com/mainproject/server/domain/chat/redis/RedisSubscriber.java
Labels: fix

#286 Dev be
  server/src/main/java/com/mainproject/server/config/RedisChatConfig.java
  server/src/main/java/com/mainproject/server/config/RedisConfig.java
  server/src/main/java/com/mainproject/server/domain/chat/entity/ChatMessage.java
  server/src/main/java/com/mainproject/server/domain/chat/redis/RedisSubscriber.java
Labels: fix

#287 #164 [BE]fix: Message 발송 메서드 반환타입 변경
  server/src/main/java/com/mainproject/server/config/RedisChatConfig.java
  server/src/main/java/com/mainproject/server/config/RedisConfig.java
  server/src/main/java/com/mainproject/server/domain/chat/controller/MessageController.java
Labels: fix

#288 #164 [BE]fix: Message 발송 메서드 반환타입 변경
  server/src/main/java/com/mainproject/server/config/RedisChatConfig.java
  server/src/main/java/com/mainproject/server/config/RedisConfig.java
  server/src/main/java/com/mainproject/server/domain/chat/controller/MessageController.java
Labels: fix

#289 #164 [BE]fix: log
  server/src/main/java/com/mainproject/server/domain/chat/controller/MessageController.java
  server/src/main/java/com/mainproject/server/domain/chat/entity/PublishMessage.java
  server/src/main/java/com/mainproject/server/domain/chat/redis/RedisPublisher.java
  server/src/main/java/com/mainproject/server/domain/chat/redis/RedisSubscriber.java
  server/src/main/java/com/mainproject/server/domain/chat/service/ChatService.java
Labels: fix

#290 Dev be
  server/src/main/java/com/mainproject/server/domain/chat/controller/MessageController.java
  server/src/main/java/com/mainproject/server/domain/chat/entity/PublishMessage.java
  server/src/main/java/com/mainproject/server/domain/chat/redis/RedisPublisher.java
  server/src/main/java/com/mainproject/server/domain/chat/redis/RedisSubscriber.java
  server/src/main/java/com/mainproject/server/domain/chat/service/ChatService.java
Labels: fix

#291 #164 [BE]fix: log
  server/src/main/java/com/mainproject/server/domain/chat/entity/PublishMessage.java
Labels: fix

#292 Dev be
  server/src/main/java/com/mainproject/server/domain/chat/entity/PublishMessage.java
Labels: fix

#295 #294 [BE]fix: Like response 추가
  server/src/main/java/com/mainproject/server/domain/LikeStatus.java
  server/src/main/java/com/mainproject/server/domain/board/controller/BoardController.java
  server/src/main/java/com/mainproject/server/domain/board/dto/BoardLikeDto.java
  server/src/main/java/com/mainproject/server/domain/board/entity/BoardLike.java
  server/src/main/java/com/mainproject/server/domain/board/mapper/BoardMapper.java
  server/src/main/java/com/mainproject/server/domain/board/service/BoardLikeService.java
  server/src/main/java/com/mainproject/server/domain/comments/controller/CommentsController.java
  server/src/main/java/com/mainproject/server/domain/comments/dto/CommentsLikeDto.java
  server/src/main/java/com/mainproject/server/domain/comments/entity/CommentsLike.java
  server/src/main/java/com/mainproject/server/domain/comments/mapper/CommentsMapper.java
  server/src/main/java/com/mainproject/server/domain/comments/service/CommentsLikeService.java
Labels: fix

#296 #294 [BE]fix: Like response 추가 (#295)
  server/src/main/java/com/mainproject/server/domain/LikeStatus.java
  server/src/main/java/com/mainproject/server/domain/board/controller/BoardController.java
  server/src/main/java/com/mainproject/server/domain/board/dto/BoardLikeDto.java
  server/src/main/java/com/mainproject/server/domain/board/entity/BoardLike.java
  server/src/main/java/com/mainproject/server/domain/board/mapper/BoardMapper.java
  server/src/main/java/com/mainproject/server/domain/board/service/BoardLikeService.java
  server/src/main/java/com/mainproject/server/domain/comments/controller/CommentsController.java
  server/src/main/java/com/mainproject/server/domain/comments/dto/CommentsLikeDto.java
  server/src/main/java/com/mainproject/server/domain/comments/entity/CommentsLike.java
  server/src/main/java/com/mainproject/server/domain/comments/mapper/CommentsMapper.java
  server/src/main/java/com/mainproject/server/domain/comments/service/CommentsLikeService.java
Labels: fix

#298 #164 [BE]fix: getrooms, getmessage pagenation 수정
  server/src/main/java/com/mainproject/server/domain/chat/controller/MessageController.java
  server/src/main/java/com/mainproject/server/domain/chat/controller/RoomController.java
  server/src/main/java/com/mainproject/server/domain/chat/service/ChatService.java
  server/src/main/java/com/mainproject/server/domain/chat/service/RoomService.java
Labels: fix

#301 #164 [BE]fix: 채팅방 topic 저장 로직 구현
  server/src/main/java/com/mainproject/server/domain/chat/controller/MessageController.java
  server/src/main/java/com/mainproject/server/domain/chat/redis/RedisPublisher.java
  server/src/main/java/com/mainproject/server/domain/chat/redis/RedisSubscriber.java
  server/src/main/java/com/mainproject/server/domain/chat/service/RoomService.java
Labels: fix

#302 #164 [BE]fix: 채팅방 topic 저장 로직 구현
  server/src/main/java/com/mainproject/server/domain/chat/controller/MessageController.java
  server/src/main/java/com/mainproject/server/domain/chat/redis/RedisPublisher.java
  server/src/main/java/com/mainproject/server/domain/chat/redis/RedisSubscriber.java
  server/src/main/java/com/mainproject/server/domain/chat/service/RoomService.java
Labels: fix

#303 #164 [BE]fix: 채팅메세지 sort 값 변경
  server/src/main/java/com/mainproject/server/domain/chat/service/ChatService.java
  server/src/main/java/com/mainproject/server/domain/chat/service/RoomService.java
Labels: fix

#304 #164 [BE]fix: 채팅메세지 sort 값 변경
  server/src/main/java/com/mainproject/server/domain/chat/service/ChatService.java
  server/src/main/java/com/mainproject/server/domain/chat/service/RoomService.java
Labels: fix

#305 #300 [BE]feat: 채팅방 조회 ResposneDto에 프로필 사진 넣기
  server/src/main/java/com/mainproject/server/domain/chat/mapper/ChatMapper.java
  server/src/main/java/com/mainproject/server/domain/member/dto/MemberDto.java
  server/src/main/java/com/mainproject/server/domain/member/mapper/MemberMapper.java
Labels: feature, fix

#306 #300 [BE]feat: 채팅방 조회 ResposneDto에 프로필 사진 넣기
  server/src/main/java/com/mainproject/server/domain/chat/mapper/ChatMapper.java
  server/src/main/java/com/mainproject/server/domain/member/dto/MemberDto.java
  server/src/main/java/com/mainproject/server/domain/member/mapper/MemberMapper.java
Labels: fix

#307 #164 [BE]fix: 메세지 조회 sort 값 변경
  server/src/main/java/com/mainproject/server/domain/chat/service/ChatService.java
Labels: fix

#308 #164 [BE]fix: 메세지 조회 sort 값 변경
  server/src/main/java/com/mainproject/server/domain/chat/service/ChatService.java
Labels: fix

#310 #309 [BE]feature: board response 좋아요한 멤버 목록 추가
  server/src/main/java/com/mainproject/server/domain/board/controller/BoardController.java
  server/src/main/java/com/mainproject/server/domain/board/dto/BoardDto.java
  server/src/main/java/com/mainproject/server/domain/board/dto/BoardLikeDto.java
  server/src/main/java/com/mainproject/server/domain/board/mapper/BoardMapper.java
  server/src/main/java/com/mainproject/server/domain/board/repository/BoardLikeRepository.java
  server/src/main/java/com/mainproject/server/domain/board/service/BoardService.java
  server/src/main/java/com/mainproject/server/domain/comments/controller/CommentsController.java
Labels: feature, fix

#311 #309 [BE]feature: board response 좋아요한 멤버 목록 추가 (#310)
  server/src/main/java/com/mainproject/server/domain/board/controller/BoardController.java
  server/src/main/java/com/mainproject/server/domain/board/dto/BoardDto.java
  server/src/main/java/com/mainproject/server/domain/board/dto/BoardLikeDto.java
  server/src/main/java/com/mainproject/server/domain/board/mapper/BoardMapper.java
  server/src/main/java/com/mainproject/server/domain/board/repository/BoardLikeRepository.java
  server/src/main/java/com/mainproject/server/domain/board/service/BoardService.java
  server/src/main/java/com/mainproject/server/domain/comments/controller/CommentsController.java
Labels: feature, fix

#314 [FE] feat: 수정 페이지에 강아지 선택 기능 추가
  client/package-lock.json
  client/package.json
  client/src/api/board/comment.js
  client/src/api/board/findMate.js
  client/src/components/GetDogInfo.js
  client/src/components/PageLoading.js
  client/src/components/boardDetail/Map.js
  client/src/components/boardDetail/MapContainer.js
  client/src/components/boardDetail/Recomment.js
  client/src/pages/BoardDetailPage.js
  client/src/pages/BoardEditPage.js
  client/src/pages/BoardPage.js
  client/src/utils/dateConvert.js
Labels: feature

#316 #315 [BE]fix: board mapper 수정
  server/src/main/java/com/mainproject/server/domain/board/mapper/BoardMapper.java
Labels: fix

#317 #315 [BE]fix: board mapper 수정
  server/src/main/java/com/mainproject/server/domain/board/mapper/BoardMapper.java
Labels: fix

#319 #318 [BE]fix: 댓글 좋아요한 멤버 response 추가
  server/src/main/java/com/mainproject/server/domain/board/service/BoardLikeService.java
  server/src/main/java/com/mainproject/server/domain/board/service/BoardService.java
  server/src/main/java/com/mainproject/server/domain/comments/dto/CommentsDto.java
  server/src/main/java/com/mainproject/server/domain/comments/entity/Comments.java
  server/src/main/java/com/mainproject/server/domain/comments/repository/CommentsLikeRepository.java
  server/src/main/java/com/mainproject/server/domain/comments/service/CommentsLikeService.java
  server/src/main/java/com/mainproject/server/domain/comments/service/CommentsService.java
Labels: fix

#320 #318 [BE]fix: 댓글 좋아요한 멤버 response 추가 (#319)
  server/src/main/java/com/mainproject/server/domain/board/service/BoardLikeService.java
  server/src/main/java/com/mainproject/server/domain/board/service/BoardService.java
  server/src/main/java/com/mainproject/server/domain/comments/dto/CommentsDto.java
  server/src/main/java/com/mainproject/server/domain/comments/entity/Comments.java
  server/src/main/java/com/mainproject/server/domain/comments/repository/CommentsLikeRepository.java
  server/src/main/java/com/mainproject/server/domain/comments/service/CommentsLikeService.java
  server/src/main/java/com/mainproject/server/domain/comments/service/CommentsService.java
Labels: fix

#322 #321 [BE]fix: timezone 설정
  server/src/main/resources/application-server.yml
Labels: bug, fix

#323 #321 [BE]fix: timezone 설정
  server/src/main/resources/application-server.yml
Labels: bug, fix

#324 #321 [BE]fix: timezone 설정
  server/src/main/java/com/mainproject/server/ServerApplication.java
Labels: bug

#325 #321 [BE]fix: timezone 설정
  server/src/main/java/com/mainproject/server/ServerApplication.java
Labels: bug
