Repository codestates-seb/seb41_main_006, pull requests merged in 2023-02, with the labels that each got.

#377 [BE] fix:#248 fix logout
  server/src/main/java/com/mainproject/server/auth/filter/JwtLogoutFilter.java
  server/src/main/java/com/mainproject/server/auth/filter/JwtReissueFilter.java
  server/src/main/resources/application-mg.yml
Labels: bug, fix

#379 [FE] fix: 글 수정 페이지 URL 오류 수정
  client/src/components/GetDogInfo.js
Labels: fix

#381 #380 [BE]fix: 댓글 프로필 이미지 수정
  server/src/main/java/com/mainproject/server/domain/board/mapper/BoardMapper.java
  server/src/main/java/com/mainproject/server/domain/comments/dto/CommentsDto.java
  server/src/main/java/com/mainproject/server/domain/comments/entity/Comments.java
  server/src/main/java/com/mainproject/server/domain/comments/mapper/CommentsMapper.java
  server/src/main/java/com/mainproject/server/domain/comments/service/CommentsService.java
Labels: bug, fix

#382 #380 [BE]fix: 댓글 프로필 이미지 수정 (#381)
  server/src/main/java/com/mainproject/server/domain/board/mapper/BoardMapper.java
  server/src/main/java/com/mainproject/server/domain/comments/dto/CommentsDto.java
  server/src/main/java/com/mainproject/server/domain/comments/entity/Comments.java
  server/src/main/java/com/mainproject/server/domain/comments/mapper/CommentsMapper.java
  server/src/main/java/com/mainproject/server/domain/comments/service/CommentsService.java
Labels: bug, fix

#384 #383 [BE]refator: channel topic 단일화
  server/src/main/java/com/mainproject/server/config/RedisConfig.java
  server/src/main/java/com/mainproject/server/domain/chat/controller/MessageController.java
  server/src/main/java/com/mainproject/server/domain/chat/controller/RoomController.java
  server/src/main/java/com/mainproject/server/domain/chat/redis/RedisPublisher.java
  server/src/main/java/com/mainproject/server/domain/chat/redis/RedisSubscriber.java
  server/src/main/java/com/mainproject/server/domain/chat/service/ChatService.java
  server/src/main/java/com/mainproject/server/domain/chat/service/RoomService.java
Labels: refator

#385 [FE] fix: 댓글 & 대댓글 프로필 사진 수정
  client/src/components/boardDetail/Comment.js
  client/src/components/boardDetail/Recomment.js
Labels: fix

#386 [Refator] chat pub/sub 개선
  server/src/main/java/com/mainproject/server/config/RedisConfig.java
  server/src/main/java/com/mainproject/server/domain/chat/controller/MessageController.java
  server/src/main/java/com/mainproject/server/domain/chat/controller/RoomController.java
  server/src/main/java/com/mainproject/server/domain/chat/redis/RedisPublisher.java
  server/src/main/java/com/mainproject/server/domain/chat/redis/RedisSubscriber.java
  server/src/main/java/com/mainproject/server/domain/chat/service/ChatService.java
  server/src/main/java/com/mainproject/server/domain/chat/service/RoomService.java
Labels: refator

#389 [BE] fix: #388 my page 500 err
  server/src/main/java/com/mainproject/server/domain/member/controller/MemberController.java
Labels: bug, fix

#391 [FE] fix: 글 작성 시 입력값 필수로 지정
  client/src/components/boardDetail/MapContainer.js
  client/src/pages/BoardPage.js
Labels: bug

#393 [BE] fix: Exception Code 수정
  server/src/main/java/com/mainproject/server/auth/filter/JwtVerificationFilter.java
  server/src/main/java/com/mainproject/server/domain/board/controller/BoardController.java
  server/src/main/java/com/mainproject/server/domain/board/service/BoardService.java
  server/src/main/java/com/mainproject/server/domain/chat/controller/MessageController.java
  server/src/main/java/com/mainproject/server/domain/chat/controller/RoomController.java
  server/src/main/java/com/mainproject/server/domain/comments/controller/CommentsController.java
  server/src/main/java/com/mainproject/server/domain/member/controller/MemberController.java
  server/src/main/java/com/mainproject/server/domain/pet/controller/PetController.java
  server/src/main/java/com/mainproject/server/domain/pet/service/PetService.java
  server/src/main/java/com/mainproject/server/exception/ExceptionCode.java
Labels: bug, fix

#396 Dev be
  server/src/main/java/com/mainproject/server/domain/board/entity/Board.java
Labels: fix

#397 #392 [BE]fix: board 매핑 변경
  server/src/main/java/com/mainproject/server/domain/board/entity/Board.java
Labels: fix

#398 Dev be
  server/src/main/java/com/mainproject/server/domain/board/entity/Board.java
Labels: fix

#399 #392 [BE]fix: boardLike, pet 매핑 변경
  server/src/main/java/com/mainproject/server/domain/board/entity/Board.java
  server/src/main/java/com/mainproject/server/domain/pet/entity/Pet.java
Labels: bug, fix

#400 Dev be
  server/src/main/java/com/mainproject/server/domain/board/entity/Board.java
  server/src/main/java/com/mainproject/server/domain/pet/entity/Pet.java
Labels: bug, fix

#401 [FE] fix: 댓글 & 대댓글 프로필 사진, 닉네임 오류 수정
  client/src/components/boardDetail/Comment.js
  client/src/components/boardDetail/Recomment.js
Labels: bug, fix

#405 #404 [BE]fix: 좋아요 관련 삭제(게시물, 댓글 및 대댓글) 수정
  server/src/main/java/com/mainproject/server/domain/board/service/BoardService.java
  server/src/main/java/com/mainproject/server/domain/comments/controller/CommentsController.java
  server/src/main/java/com/mainproject/server/domain/comments/entity/Comments.java
  server/src/main/java/com/mainproject/server/domain/comments/service/CommentsService.java
Labels: bug, fix

#406 #404 [BE]fix: 좋아요 관련 삭제(게시물, 댓글 및 대댓글) 수정 (#405)
  server/src/main/java/com/mainproject/server/domain/board/service/BoardService.java
  server/src/main/java/com/mainproject/server/domain/comments/controller/CommentsController.java
  server/src/main/java/com/mainproject/server/domain/comments/entity/Comments.java
  server/src/main/java/com/mainproject/server/domain/comments/service/CommentsService.java
Labels: bug, fix

#408 [FE] fix: 글 작성 오류 수정
  client/src/components/AccessBlockModal.js
  client/src/components/GlobalModal.js
  client/src/components/boardDetail/Map.js
  client/src/components/boardDetail/MapContainer.js
  client/src/components/findMate/MateBoardContent.js
  client/src/pages/BoardDetailPage.js
  client/src/pages/BoardPage.js
Labels: bug, fix

#412 #392 [BE]fix: cascade 삭제
  server/src/main/java/com/mainproject/server/domain/board/entity/Board.java
  server/src/main/java/com/mainproject/server/domain/board/entity/BoardLike.java
  server/src/main/java/com/mainproject/server/domain/comments/entity/Comments.java
  server/src/main/java/com/mainproject/server/domain/comments/entity/CommentsLike.java
  server/src/main/java/com/mainproject/server/domain/pet/entity/Pet.java
Labels: bug, fix

#413 Dev be
  server/src/main/java/com/mainproject/server/domain/board/entity/Board.java
  server/src/main/java/com/mainproject/server/domain/board/entity/BoardLike.java
  server/src/main/java/com/mainproject/server/domain/comments/entity/Comments.java
  server/src/main/java/com/mainproject/server/domain/comments/entity/CommentsLike.java
  server/src/main/java/com/mainproject/server/domain/pet/entity/Pet.java
Labels: bug, fix

#416 [FE] fix: 보드 오류 수정
  client/src/api/board/findMate.js
  client/src/components/GetDogInfo.js
  client/src/components/boardDetail/Map.js
  client/src/components/boardDetail/MapContainer.js
  client/src/hooks/useFetch.js
  client/src/pages/BoardEditPage.js
  client/src/pages/BoardPage.js
Labels: bug, fix

#425 #424 [BE]documentation: 댓글,대댓글,좋아요,S3 관련 주석 추가
  server/src/main/java/com/mainproject/server/awsS3/service/S3UpFileService.java
  server/src/main/java/com/mainproject/server/domain/board/controller/BoardController.java
  server/src/main/java/com/mainproject/server/domain/board/service/BoardLikeService.java
  server/src/main/java/com/mainproject/server/domain/comments/controller/CommentsController.java
  server/src/main/java/com/mainproject/server/domain/comments/service/CommentsLikeService.java
  server/src/main/java/com/mainproject/server/domain/comments/service/CommentsService.java
Labels: documentation

#426 #424 [BE]documentation: 댓글,대댓글,좋아요,S3 관련 주석 추가
  server/src/main/java/com/mainproject/server/awsS3/service/S3UpFileService.java
  server/src/main/java/com/mainproject/server/domain/board/controller/BoardController.java
  server/src/main/java/com/mainproject/server/domain/board/service/BoardLikeService.java
  server/src/main/java/com/mainproject/server/domain/comments/controller/CommentsController.java
  server/src/main/java/com/mainproject/server/domain/comments/service/CommentsLikeService.java
  server/src/main/java/com/mainproject/server/domain/comments/service/CommentsService.java
Labels: documentation

#427 #424 [BE]documentation: 댓글,대댓글,좋아요,S3 관련 주석 추가
  server/src/main/java/com/mainproject/server/awsS3/service/S3UpFileService.java
  server/src/main/java/com/mainproject/server/domain/board/controller/BoardController.java
  server/src/main/java/com/mainproject/server/domain/board/service/BoardLikeService.java
  server/src/main/java/com/mainproject/server/domain/comments/controller/CommentsController.java
  server/src/main/java/com/mainproject/server/domain/comments/service/CommentsLikeService.java
  server/src/main/java/com/mainproject/server/domain/comments/service/CommentsService.java
Labels: documentation
